#### Задача 1

Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [2]:
import numpy as np
from scipy import stats

In [3]:
a = np.array([173, 175, 180, 178, 177, 185, 183, 182])
a

array([173, 175, 180, 178, 177, 185, 183, 182])

In [4]:
b = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
b

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [5]:
c = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
c

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [12]:
stats.f_oneway(a, b, c)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

Видим, что значение pvalue=0.010482206918698694 меньше уровня статистической значимости 0.05, значит принимаем альтернативную гипотезу H1, то есть рост спортсменов зависит от вида спорта.