In [1]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import _tconfint_generic as t_stat
from scipy.stats import norm
from scipy import stats
import math

#### Задача 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [4]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110]) 

In [5]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]) 

Математическое ожидание заработной платы заемщиков банка.

In [6]:
mean_zp = zp.mean()
mean_zp

101.4

Математическое ожидание их кредитнго скоринга

In [7]:
mean_ks = ks.mean()
mean_ks

709.9

Математическое ожидание произведения случайных величин

In [10]:
mean_zp_ks = (zp * ks).mean()
mean_zp_ks

81141.7

Ковариация

In [11]:
cov_zp_ks = mean_zp_ks - mean_zp * mean_ks
cov_zp_ks

9157.839999999997

Ковариация с помощью встроенной функции

In [21]:
X = np.stack((zp, ks), axis = 0)
X

array([[ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110],
       [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]])

In [27]:
cov_zp_ks_matrix = np.cov(X, ddof=0)
cov_zp_ks_matrix

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [28]:
cov_zp_ks_matrix[0, 1]

9157.84

Среднеквадратичные отклонения величин

In [36]:
std_zp = zp.std(ddof=0)
std_zp

59.115480206118605

In [37]:
std_ks = ks.std(ddof=0)
std_ks

174.55340157098058

Коэффициент корреляции Пирсона

In [38]:
corr_zp_ks = cov_zp_ks / (std_zp * std_ks)
corr_zp_ks

0.8874900920739158

In [49]:
corr_zp_ks_matrix = np.corrcoef(X)
corr_zp_ks_matrix

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [48]:
corr_zp_ks = corr_zp_ks_matrix[0, 1]
corr_zp_ks

0.8874900920739162

С помощью pandas

In [53]:
df = pd.DataFrame({'zp': zp, 'ks': ks})
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [54]:
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

#### Задача 2

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [55]:
data = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
data

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

Объем выборки

In [56]:
n = data.size
n

10

In [57]:
a = 0.95
a

0.95

Среднеквадратичное отклонение

In [58]:
sigma = data.std(ddof = 1)
sigma

10.54566788359614

Среднее

In [59]:
m = data.mean()
m

118.1

Правая граница t-критерия

In [64]:
t_obj = stats.t(n - 1)
zr = t_obj.ppf(0.975)
zr

2.2621571627409915

Левая граница t-критерия

In [66]:
zl = t_obj.ppf(0.025)
zl

-2.262157162740992

Доверительный интервал

In [67]:
(m + zl * sigma / np.sqrt(n), m + zr * sigma / np.sqrt(n))

(110.55608365158724, 125.64391634841274)

#### Задача 3

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

Объем выборки

In [68]:
n = 27
n

27

Среднее выборочное

In [77]:
m = 174.2

Стандартное отклонение

In [75]:
sigma = 5

Левая граница Z-критерия

In [72]:
zr = norm.ppf(0.975)
zr

1.959963984540054

Правая граница Z-критерия

In [73]:
zl = norm.ppf(0.025)
zl

-1.9599639845400545

Доверительный интервал

In [78]:
(m + zl * sigma / np.sqrt(n), m + zr * sigma / np.sqrt(n))

(172.3140237765397, 176.08597622346028)